01. <html>
<head>
<title>Programa que retorna o valor absoluto de um número</title>
</head>
Autor: Thalyta

<body>
  <script>
    var valor1 = Math.abs (-1234);
    alert (valor1);
  </script>
</body>
</html>



02.
<html>
<head>
<title>...</title>
</head>

<body>
  <script>
    var valor1 = Math.acos (0.14);
    alert (valor1);
  </script>
</body>
</html>


03.
<html>
<head>
<title>...</title>
</head>

<body>
  <script>
    var valor1 = Math.acos (0.14);
    alert (valor1);
  </script>
</body>
</html>
